Repository assap-org/assap, pull requests merged in 2019-11, with the labels that each got.

#61 Check identification
  src/components/Camera.vue
  src/components/Wizard.vue
  src/utils/configuration.js
  src/utils/descriptors.js
  src/views/Home.vue
Labels: enhancement

#62 Front fixes
  src/components/Camera.vue
  src/components/Menu.vue
  src/components/Password.vue
  src/main.js
  src/views/Home.vue
Labels: enhancement

#63 fixed states of the camera
  src/components/Camera.vue
  src/components/SettingNav.vue
  src/components/Wizard.vue
  src/views/Home.vue
Labels: bug, enhancement

#64 Assap/dev fix login forms
  src/components/Password.vue
Labels: bug

#65 Assap/dev cipher facial init
  src/components/Camera.vue
  src/components/Menu.vue
  src/components/Password.vue
  src/main.js
  src/utils/configuration.js
Labels: enhancement
